### ISSUE TITLE
Day names?

### ISSUE THREAD

**Issue by jvraines** [joakim/calendar#3]
Do you have any proposal for naming the days of the nonad ("week")?

**Comment by joakim** [comment]
First, thanks for checking out the calendar. You're the first to comment on it :)

> Do you have any proposal for naming the days of the nonad ("week")?

Actually no. I have thought about it, and have considered the planets of our solar system, of course[^1]. But I'd rather keep the calendar "parts" unnamed, and leave it to anyone who adopts the calendar to come up with names. Partly because I want to focus on the design of the calendar itself, but also because it would tie it to one language/culture. By naming you make it yours.

Even terms like _nonad_ are descriptive only. It could be called something else. But I call it nonad. And personally, I tend to call the days of the nonad "day one", "day two", etc. Sometimes I say "onesday", "twosday", etc. :)

[^1]: Without Pluto, the ninth could be either the Sun, the Moon or the elusive [Planet Nine](https://en.wikipedia.org/wiki/Planet_Nine).
